package com.dvid.dcam.app;

public enum Screen {
    CAMERA, MENU, FILES, RECORD_SETTINGS, USER_SETTINGS, SERVER_SETTINGS,
    STORAGE_SETTINGS, DEVICE_SETTINGS, AUDIO_SETTINGS, CAMERA_SETTINGS, ABOUT
}
