package com.dvid.dcam.feature.settings.presentation;

/** Stable IDs for settings controls shown by the settings presentation layer. */
public enum SettingId {
    RECORD_RESOLUTION,
    VIDEO_SEGMENT_LENGTH_MINUTES,
    LOOP_RECORDING,
    DEFAULT_STORAGE,
    LOW_STORAGE_WARNING_GB,
    RECYCLE_OLD_RECORDINGS,
    ENCRYPT_VIDEO_FILES,
    PROTECT_SETTINGS_MENU,
    USB_ACCESS_PROTECTION,
    CHANGE_OPERATOR_ID,
    CHANGE_OPERATOR_PASSWORD,
    LOGOUT,
    FULL_SCREEN_DISPLAY,
    STATUS_LIGHTS,
    LANGUAGE,
    FEATURE_IMAGE_CAPTURE,
    FEATURE_VIDEO_CAPTURE,
    FEATURE_AUDIO_CAPTURE,
    FEATURE_MEDIA_BROWSER,
    FEATURE_RECORDING_SETTINGS,
    FEATURE_CAMERA_SETTINGS,
    FEATURE_AUDIO_SETTINGS,
    FEATURE_STORAGE_SETTINGS,
    FEATURE_DEVICE_SETTINGS,
    FEATURE_GPS,
    FEATURE_SECURITY_SETTINGS,
    FEATURE_CLOUD_SETTINGS,
    FEATURE_TRANSFER,
    FEATURE_VIDEO_STREAMING
}
