-- DCAM database DDL v1 design reference
-- Status: proposal; not executed by the application yet.
-- Time values are UTC Unix epoch milliseconds unless the column says elapsed_realtime_ms.
-- UUID values are canonical lowercase text generated by the application.
--
-- Room also manages PRAGMA user_version and room_master_table. schema_version below is the
-- application/BDMA compatibility contract and must agree with Room's exported schema version.

PRAGMA foreign_keys = ON;

CREATE TABLE schema_version (
    singleton_id INTEGER NOT NULL PRIMARY KEY CHECK (singleton_id = 1),
    sqlite_schema_version INTEGER NOT NULL,
    schema_name TEXT NOT NULL,
    app_code TEXT NOT NULL,
    app_package_name TEXT NOT NULL,
    app_version_name TEXT NOT NULL,
    app_version_code INTEGER NOT NULL,
    dcam_data_contract_version TEXT NOT NULL,
    media_contract_version TEXT NOT NULL,
    encoder_contract_version TEXT NOT NULL,
    created_at_ms INTEGER NOT NULL,
    migrated_at_ms INTEGER NOT NULL,
    minimum_bdma_schema_version INTEGER,
    compatibility_status TEXT NOT NULL DEFAULT 'COMPATIBLE',
    revision INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE device_identity (
    singleton_id INTEGER NOT NULL PRIMARY KEY CHECK (singleton_id = 1),
    dcam_cloud_device_id TEXT,
    android_id_hash TEXT NOT NULL,
    serial_number TEXT,
    device_name TEXT,
    model TEXT,
    manufacturer TEXT,
    owner_name TEXT,
    manufacture_date TEXT,
    firmware_version TEXT,
    hardware_version TEXT,
    identity_status TEXT NOT NULL DEFAULT 'LOCAL_ONLY',
    identity_source TEXT NOT NULL DEFAULT 'DEVICE',
    server_revision TEXT,
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1
);

CREATE UNIQUE INDEX uq_device_identity_cloud_id
    ON device_identity(dcam_cloud_device_id)
    WHERE dcam_cloud_device_id IS NOT NULL;

CREATE UNIQUE INDEX uq_device_identity_android_hash
    ON device_identity(android_id_hash);

CREATE TABLE provisioning_state (
    singleton_id INTEGER NOT NULL PRIMARY KEY CHECK (singleton_id = 1),
    state TEXT NOT NULL DEFAULT 'PROVISIONING_REQUIRED',
    reason_code TEXT,
    server_environment TEXT,
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    last_attempt_at_ms INTEGER,
    activated_at_ms INTEGER,
    failed_at_ms INTEGER,
    last_error_redacted TEXT,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE user_profile (
    user_id TEXT NOT NULL PRIMARY KEY,
    file_user_id TEXT NOT NULL,
    display_name TEXT NOT NULL,
    badge_number TEXT,
    role_code TEXT NOT NULL DEFAULT 'OPERATOR',
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    source TEXT NOT NULL DEFAULT 'LOCAL',
    server_revision TEXT,
    valid_from_ms INTEGER,
    valid_until_ms INTEGER,
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL,
    deleted_at_ms INTEGER,
    revision INTEGER NOT NULL DEFAULT 1,
    CHECK (length(file_user_id) = 6)
);

CREATE UNIQUE INDEX uq_user_profile_file_user_id
    ON user_profile(file_user_id);

CREATE INDEX ix_user_profile_status
    ON user_profile(status, updated_at_ms);

CREATE INDEX ix_user_profile_server_revision
    ON user_profile(server_revision);

CREATE TABLE user_auth_method (
    auth_method_id TEXT NOT NULL PRIMARY KEY,
    user_id TEXT NOT NULL,
    method_type TEXT NOT NULL,
    credential_algorithm TEXT NOT NULL,
    credential_version INTEGER NOT NULL DEFAULT 1,
    credential_blob BLOB,
    keystore_alias TEXT,
    parameters_json TEXT,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    failed_attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (failed_attempt_count >= 0),
    locked_until_ms INTEGER,
    last_used_at_ms INTEGER,
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL,
    revoked_at_ms INTEGER,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE INDEX ix_user_auth_method_user
    ON user_auth_method(user_id, status, method_type);

CREATE UNIQUE INDEX uq_user_auth_method_active_type
    ON user_auth_method(user_id, method_type)
    WHERE status = 'ACTIVE';

CREATE TABLE operator_session (
    operator_session_id TEXT NOT NULL PRIMARY KEY,
    user_id TEXT,
    identity_type TEXT NOT NULL,
    operator_id_snapshot TEXT NOT NULL,
    file_user_id_snapshot TEXT NOT NULL,
    display_name_snapshot TEXT NOT NULL,
    role_snapshot TEXT NOT NULL,
    auth_method_id TEXT,
    boot_id TEXT NOT NULL,
    process_instance_id TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'ACTIVE',
    started_at_ms INTEGER NOT NULL,
    started_elapsed_realtime_ms INTEGER,
    ended_at_ms INTEGER,
    end_reason_code TEXT,
    last_activity_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (user_id) REFERENCES user_profile(user_id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (auth_method_id) REFERENCES user_auth_method(auth_method_id)
        ON UPDATE CASCADE ON DELETE SET NULL,
    CHECK (length(file_user_id_snapshot) = 6)
);

CREATE UNIQUE INDEX uq_operator_session_one_active
    ON operator_session((1))
    WHERE status = 'ACTIVE';

CREATE INDEX ix_operator_session_user_time
    ON operator_session(user_id, started_at_ms DESC);

CREATE INDEX ix_operator_session_boot_status
    ON operator_session(boot_id, status);

CREATE TABLE operational_setting (
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL DEFAULT '',
    setting_key TEXT NOT NULL,
    value_type TEXT NOT NULL,
    requested_value TEXT,
    source TEXT NOT NULL DEFAULT 'DEFAULT',
    source_revision TEXT,
    updated_by_operator_id TEXT,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (scope_type, scope_id, setting_key)
);

CREATE INDEX ix_operational_setting_updated
    ON operational_setting(updated_at_ms);

CREATE TABLE applied_setting_state (
    scope_type TEXT NOT NULL,
    scope_id TEXT NOT NULL DEFAULT '',
    setting_key TEXT NOT NULL,
    requested_revision INTEGER NOT NULL,
    applied_value TEXT,
    apply_status TEXT NOT NULL,
    reason_code TEXT,
    applied_at_ms INTEGER,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (scope_type, scope_id, setting_key),
    FOREIGN KEY (scope_type, scope_id, setting_key)
        REFERENCES operational_setting(scope_type, scope_id, setting_key)
        ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE INDEX ix_applied_setting_status
    ON applied_setting_state(apply_status, updated_at_ms);

CREATE TABLE feature_eligibility_state (
    feature_key TEXT NOT NULL PRIMARY KEY,
    requested_enabled INTEGER NOT NULL DEFAULT 1 CHECK (requested_enabled IN (0, 1)),
    capability_available INTEGER NOT NULL DEFAULT 0 CHECK (capability_available IN (0, 1)),
    effective_enabled INTEGER NOT NULL DEFAULT 0 CHECK (effective_enabled IN (0, 1)),
    status TEXT NOT NULL,
    reason_code TEXT,
    capability_fingerprint TEXT,
    evaluated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX ix_feature_eligibility_effective
    ON feature_eligibility_state(effective_enabled, status);

CREATE TABLE app_runtime_state (
    singleton_id INTEGER NOT NULL PRIMARY KEY CHECK (singleton_id = 1),
    boot_id TEXT NOT NULL,
    process_instance_id TEXT NOT NULL,
    runtime_mode TEXT NOT NULL DEFAULT 'INITIALIZING',
    startup_reason TEXT NOT NULL,
    active_operator_session_id TEXT,
    active_media_session_id TEXT,
    recovery_required INTEGER NOT NULL DEFAULT 0 CHECK (recovery_required IN (0, 1)),
    safe_mode_reason_code TEXT,
    last_start_at_ms INTEGER NOT NULL,
    last_heartbeat_at_ms INTEGER,
    last_clean_shutdown_at_ms INTEGER,
    last_error_reason_code TEXT,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (active_operator_session_id)
        REFERENCES operator_session(operator_session_id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (active_media_session_id)
        REFERENCES media_session(media_session_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX ix_app_runtime_boot
    ON app_runtime_state(boot_id, runtime_mode);

CREATE TABLE media_session (
    media_session_id TEXT NOT NULL PRIMARY KEY,
    request_id TEXT NOT NULL,
    media_type TEXT NOT NULL,
    capture_mode TEXT NOT NULL,
    importance TEXT NOT NULL DEFAULT 'NORMAL',
    state TEXT NOT NULL,
    operator_session_id TEXT,
    operator_id_snapshot TEXT NOT NULL,
    file_user_id_snapshot TEXT NOT NULL,
    operator_name_snapshot TEXT NOT NULL,
    operator_role_snapshot TEXT NOT NULL,
    camera_id_snapshot TEXT NOT NULL,
    device_id_snapshot TEXT,
    boot_id TEXT NOT NULL,
    process_instance_id TEXT NOT NULL,
    storage_root TEXT NOT NULL,
    staging_relative_path TEXT NOT NULL,
    final_relative_path TEXT,
    final_file_name TEXT,
    mime_type TEXT NOT NULL,
    requested_at_ms INTEGER NOT NULL,
    started_at_ms INTEGER,
    started_elapsed_realtime_ms INTEGER,
    stop_requested_at_ms INTEGER,
    stopped_at_ms INTEGER,
    completed_at_ms INTEGER,
    duration_ms INTEGER,
    size_bytes INTEGER,
    is_encrypted INTEGER NOT NULL DEFAULT 0 CHECK (is_encrypted IN (0, 1)),
    error_reason_code TEXT,
    error_detail_redacted TEXT,
    recovery_disposition TEXT,
    created_at_ms INTEGER NOT NULL,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (operator_session_id)
        REFERENCES operator_session(operator_session_id) ON UPDATE CASCADE ON DELETE SET NULL,
    CHECK (length(file_user_id_snapshot) = 6),
    CHECK (length(camera_id_snapshot) BETWEEN 6 AND 10),
    CHECK (size_bytes IS NULL OR size_bytes >= 0),
    CHECK (duration_ms IS NULL OR duration_ms >= 0)
);

CREATE UNIQUE INDEX uq_media_session_request
    ON media_session(request_id);

CREATE UNIQUE INDEX uq_media_session_final_path
    ON media_session(storage_root, final_relative_path)
    WHERE final_relative_path IS NOT NULL;

CREATE INDEX ix_media_session_state_updated
    ON media_session(state, updated_at_ms);

CREATE INDEX ix_media_session_operator_time
    ON media_session(operator_id_snapshot, requested_at_ms DESC);

CREATE INDEX ix_media_session_bdma_scan
    ON media_session(completed_at_ms, media_type)
    WHERE state = 'COMPLETED';

CREATE TABLE recording_lease (
    singleton_id INTEGER NOT NULL PRIMARY KEY CHECK (singleton_id = 1),
    media_session_id TEXT,
    owner_boot_id TEXT,
    owner_process_instance_id TEXT,
    lease_generation INTEGER NOT NULL DEFAULT 0 CHECK (lease_generation >= 0),
    acquired_at_ms INTEGER,
    heartbeat_at_ms INTEGER,
    expires_at_ms INTEGER,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (media_session_id)
        REFERENCES media_session(media_session_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE UNIQUE INDEX uq_recording_lease_session
    ON recording_lease(media_session_id)
    WHERE media_session_id IS NOT NULL;

CREATE TABLE foreground_service_state (
    service_key TEXT NOT NULL PRIMARY KEY,
    state TEXT NOT NULL,
    start_reason TEXT,
    active_media_session_id TEXT,
    owner_boot_id TEXT,
    owner_process_instance_id TEXT,
    started_at_ms INTEGER,
    last_heartbeat_at_ms INTEGER,
    stopped_at_ms INTEGER,
    restart_count INTEGER NOT NULL DEFAULT 0 CHECK (restart_count >= 0),
    last_error_reason_code TEXT,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (active_media_session_id)
        REFERENCES media_session(media_session_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX ix_foreground_service_state
    ON foreground_service_state(state, last_heartbeat_at_ms);

CREATE TABLE media_finalization_state (
    media_session_id TEXT NOT NULL PRIMARY KEY,
    stage TEXT NOT NULL,
    staging_relative_path TEXT NOT NULL,
    target_relative_path TEXT,
    source_size_bytes INTEGER,
    source_modified_at_ms INTEGER,
    validation_status TEXT NOT NULL DEFAULT 'NOT_RUN',
    encryption_status TEXT NOT NULL DEFAULT 'NOT_REQUESTED',
    encryption_algorithm TEXT,
    checksum_status TEXT NOT NULL DEFAULT 'NOT_REQUESTED',
    checksum_algorithm TEXT,
    checksum_hex TEXT,
    checksum_relative_path TEXT,
    publish_status TEXT NOT NULL DEFAULT 'NOT_STARTED',
    bdma_ready INTEGER NOT NULL DEFAULT 0 CHECK (bdma_ready IN (0, 1)),
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    started_at_ms INTEGER,
    completed_at_ms INTEGER,
    last_attempt_at_ms INTEGER,
    last_error_reason_code TEXT,
    last_error_detail_redacted TEXT,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (media_session_id)
        REFERENCES media_session(media_session_id) ON UPDATE CASCADE ON DELETE CASCADE,
    CHECK (source_size_bytes IS NULL OR source_size_bytes >= 0)
);

CREATE INDEX ix_media_finalization_recovery
    ON media_finalization_state(bdma_ready, stage, updated_at_ms);

CREATE TABLE media_session_event (
    event_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    media_session_id TEXT NOT NULL,
    sequence_no INTEGER NOT NULL CHECK (sequence_no >= 1),
    event_type TEXT NOT NULL,
    from_state TEXT,
    to_state TEXT,
    reason_code TEXT,
    event_at_ms INTEGER NOT NULL,
    elapsed_realtime_ms INTEGER,
    boot_id TEXT NOT NULL,
    process_instance_id TEXT NOT NULL,
    detail_json_redacted TEXT,
    FOREIGN KEY (media_session_id)
        REFERENCES media_session(media_session_id) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE UNIQUE INDEX uq_media_session_event_sequence
    ON media_session_event(media_session_id, sequence_no);

CREATE INDEX ix_media_session_event_time
    ON media_session_event(event_at_ms);

CREATE TABLE media_import_state (
    media_import_id TEXT NOT NULL PRIMARY KEY,
    media_session_id TEXT NOT NULL,
    consumer_id TEXT NOT NULL DEFAULT 'BDMA',
    consumer_version TEXT,
    attempt_no INTEGER NOT NULL CHECK (attempt_no >= 1),
    state TEXT NOT NULL,
    verification_status TEXT,
    source_revision INTEGER NOT NULL,
    requested_at_ms INTEGER,
    started_at_ms INTEGER,
    completed_at_ms INTEGER,
    cleanup_eligible INTEGER NOT NULL DEFAULT 0 CHECK (cleanup_eligible IN (0, 1)),
    source_deleted INTEGER NOT NULL DEFAULT 0 CHECK (source_deleted IN (0, 1)),
    source_deleted_at_ms INTEGER,
    error_code TEXT,
    error_detail_redacted TEXT,
    updated_at_ms INTEGER NOT NULL,
    revision INTEGER NOT NULL DEFAULT 1,
    FOREIGN KEY (media_session_id)
        REFERENCES media_session(media_session_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    UNIQUE (media_session_id, consumer_id, attempt_no)
);

CREATE INDEX ix_media_import_pending
    ON media_import_state(consumer_id, state, updated_at_ms);

CREATE TABLE external_change_request (
    request_id TEXT NOT NULL PRIMARY KEY,
    producer TEXT NOT NULL,
    producer_version TEXT,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    expected_revision INTEGER,
    payload_schema_version INTEGER NOT NULL DEFAULT 1,
    payload_json TEXT NOT NULL,
    requested_at_ms INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    processed_at_ms INTEGER,
    result_revision INTEGER,
    result_code TEXT,
    result_detail_redacted TEXT
);

CREATE INDEX ix_external_change_request_pending
    ON external_change_request(status, requested_at_ms);

CREATE TABLE external_change_log (
    change_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    request_id TEXT,
    source TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id TEXT NOT NULL,
    operation TEXT NOT NULL,
    before_revision INTEGER,
    after_revision INTEGER,
    result TEXT NOT NULL,
    reason_code TEXT,
    changed_at_ms INTEGER NOT NULL,
    payload_hash TEXT,
    detail_json_redacted TEXT,
    FOREIGN KEY (request_id)
        REFERENCES external_change_request(request_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX ix_external_change_log_target
    ON external_change_log(target_type, target_id, changed_at_ms DESC);

CREATE INDEX ix_external_change_log_time
    ON external_change_log(changed_at_ms);

CREATE TABLE remote_config_cache (
    singleton_id INTEGER NOT NULL PRIMARY KEY CHECK (singleton_id = 1),
    source TEXT,
    revision TEXT,
    payload_schema_version INTEGER,
    payload_json TEXT,
    signature TEXT,
    status TEXT NOT NULL DEFAULT 'NONE',
    received_at_ms INTEGER,
    validated_at_ms INTEGER,
    applied_at_ms INTEGER,
    last_error_code TEXT,
    last_error_redacted TEXT,
    revision_counter INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE diagnostic_event (
    diagnostic_event_id TEXT NOT NULL PRIMARY KEY,
    event_at_ms INTEGER NOT NULL,
    elapsed_realtime_ms INTEGER,
    severity TEXT NOT NULL,
    category TEXT NOT NULL,
    reason_code TEXT NOT NULL,
    boot_id TEXT,
    process_instance_id TEXT,
    operator_session_id TEXT,
    media_session_id TEXT,
    message_redacted TEXT,
    detail_json_redacted TEXT,
    created_at_ms INTEGER NOT NULL,
    FOREIGN KEY (operator_session_id)
        REFERENCES operator_session(operator_session_id) ON UPDATE CASCADE ON DELETE SET NULL,
    FOREIGN KEY (media_session_id)
        REFERENCES media_session(media_session_id) ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE INDEX ix_diagnostic_event_time
    ON diagnostic_event(event_at_ms);

CREATE INDEX ix_diagnostic_event_reason
    ON diagnostic_event(reason_code, event_at_ms DESC);

CREATE INDEX ix_diagnostic_event_media
    ON diagnostic_event(media_session_id, event_at_ms);

-- Provider-specific delivery queue. This is infrastructure, not the diagnostic/audit contract.
CREATE TABLE pending_logs (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    event_id TEXT NOT NULL,
    created_at_ms INTEGER NOT NULL,
    level TEXT NOT NULL,
    payload TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'PENDING',
    attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
    next_attempt_at_ms INTEGER,
    first_failed_at_ms INTEGER,
    last_error_redacted TEXT
);

CREATE UNIQUE INDEX uq_pending_logs_event
    ON pending_logs(event_id);

CREATE INDEX ix_pending_logs_delivery
    ON pending_logs(status, next_attempt_at_ms, id);

-- Stable, versioned BDMA read surface. Add v2 views for breaking changes; never silently change
-- the meaning of a released view.
CREATE VIEW bdma_schema_info_v1 AS
SELECT
    sqlite_schema_version,
    schema_name,
    app_code,
    app_package_name,
    app_version_name,
    app_version_code,
    dcam_data_contract_version,
    media_contract_version,
    encoder_contract_version,
    compatibility_status,
    revision
FROM schema_version
WHERE singleton_id = 1;

CREATE VIEW bdma_media_v1 AS
SELECT
    m.media_session_id,
    m.media_type,
    m.capture_mode,
    m.importance,
    m.operator_id_snapshot,
    m.file_user_id_snapshot,
    m.operator_name_snapshot,
    m.camera_id_snapshot,
    m.storage_root,
    m.final_relative_path,
    m.final_file_name,
    m.mime_type,
    m.started_at_ms,
    m.completed_at_ms,
    m.duration_ms,
    m.size_bytes,
    m.is_encrypted,
    f.checksum_status,
    f.checksum_algorithm,
    f.checksum_hex,
    f.checksum_relative_path,
    f.bdma_ready,
    m.revision AS media_revision
FROM media_session AS m
JOIN media_finalization_state AS f
  ON f.media_session_id = m.media_session_id
WHERE m.state = 'COMPLETED'
  AND f.bdma_ready = 1;

CREATE VIEW bdma_user_v1 AS
SELECT
    user_id,
    file_user_id,
    display_name,
    badge_number,
    role_code,
    status,
    source,
    server_revision,
    valid_from_ms,
    valid_until_ms,
    updated_at_ms,
    revision
FROM user_profile;

-- Seed singleton rows in the same transaction that creates or migrates the database.
-- Concrete version/build/contract values are supplied by the application, not hardcoded here.
INSERT INTO recording_lease (
    singleton_id,
    media_session_id,
    lease_generation,
    revision
) VALUES (1, NULL, 0, 1);
